apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.6.1
        ports:
        - containerPort: 8080
        env:
        - name: CATALOG_ENDPOINT
          value: "http://catalog"
        - name: ORDERS_ENDPOINT
          value: "http://orders"
        - name: CARTS_ENDPOINT
          value: "http://carts"
        - name: CHECKOUT_ENDPOINT
          value: "http://checkout"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ui
