apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-db
  namespace: retail-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: catalog-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: project-bedrock/catalog-mysql
        property: username
    - secretKey: password
      remoteRef:
        key: project-bedrock/catalog-mysql
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-db
  namespace: retail-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: orders-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: project-bedrock/orders-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: project-bedrock/orders-postgres
        property: password
